[pytest]
markers =
    login: Login tests
    inventory: Inventory page tests
    product: Product detail tests
    cart: Cart tests
    checkout: Checkout flow tests
    menu: Menu tests
    footer: Footer tests
    security: Security tests
    e2e: End-to-end tests

addopts =
    --html=reports/report.html
    --self-contained-html
    --reruns=1
    --reruns-delay=2
    -v

testpaths = tests
