[pytest]
markers =
    login: Login functionality tests
    inventory: Inventory page tests
    product: Product detail tests
    cart: Shopping cart tests
    checkout: Checkout flow tests
    menu: Hamburger menu tests
    footer: Footer tests
    security: URL / security tests
    e2e: End-to-end flow tests
    smoke: Smoke tests
    regression: Regression tests

addopts = --html=reports/report.html --self-contained-html -v
testpaths = tests
